// Characters
export const FORM_CHARACTERS_FILTER_ID = 'FORM_CHARACTERS_FILTER';

// Locations
export const FORM_LOCATIONS_FILTER_ID = 'FORM_LOCATIONS_FILTER';

// Episodes
export const FORM_EPISODES_FILTER_ID = 'FORM_EPISODES_FILTER';
